spring:
  application:
    name: simplecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/simplecommercedb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update  # Can be 'none', 'update', or 'create'
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 3000
